### ISSUE TITLE
Project does not run in gradle

### ISSUE THREAD

**Issue by DarkStar1** [rmondejar/spring-boot-junit5-example#2]
I cloned the project and any attempt to fire it up results in the following message:
`gradle-or-gradlew:17: command not found: gradle`

**Comment by rmondejar** [comment]
hey @DarkStar1,

You should install **gradle** first: https://gradle.org/install/

In any case, I just updated the project with **gradle wrapper**, now you can follow the instructions without install anything else.

Reminder: the project also supports **maven**
